version: 2
catalog:
  name: MySQL
  version: 5.7-rancher1
  upgrade_from: 0.5-rancher1
  description: |
    MySQL Server 5.7
  questions:
    - variable: MYSQL_PORT
      label: MySQL Host port mapping
      description: |
        MySQL Host port mapping
      required: true
      default: 3306
      type: int
    - variable: MYSQL_DATA
      label: MySQL DATA Volume
      description: |
        MySQL DATA DIR
      required: true
      default: '/var/lib/docker-mysql'
      type: string
    - variable: MYSQL_ROOT_PASSWORD
      label: MySQL root password
      description: |
        MySQL root password
      required: true
      default: 'root_password'
      type: string
    - variable: MYSQL_DATABASE
      label: MySQL default database
      description: |
        MySQL default database
      required: true
      default: 'defaultdatabase'
      type: string
    - variable: MYSQL_USER
      label: MySQL user name
      description: |
        MySQL user name
      required: true
      default: 'user_name'
      type: string
    - variable: MYSQL_PASSWORD
      label: MySQL user password
      description: |
        MySQL user password
      required: true
      default: 'user_password'
      type: string

services:
  mysql:
    retain_ip: true
    scale: 1
    start_on_create: true
