version: '2'
services:
  rancherdb-backup:
    image: teknologist/mysql-backup
    hostname: rancherdb-backup
    volumes:
    - ${DB_DUMP_TARGET}:/db
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAMES: ${DB_NAMES}
      DB_USER: ${CATTLEDB_USER}
      DB_PASS: ${CATTLEDB_USER_PASSWORD}
      DB_DUMP_FREQ: ${DB_DUMP_FREQ}
      DB_DUMP_BEGIN: ${DB_DUMP_BEGIN}
      DB_DUMP_TARGET: ${DB_DUMP_TARGET}
      DB_DUMP_DEBUG: ${DB_DUMP_DEBUG}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
