version: '2'
services:
  rancherdb-backup:
    image: teknologist/mysql-backup
    hostname: rancherdb-backup
    {{- if eq .Values.DB_DUMP_TARGET_REMOTE "false"}}
    volumes:
    - ${DB_DUMP_TARGET}:/backup
    {{- end }}
    - ${LOCAL_SCRIPTS}:/scripts.d/post-backup:ro
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAMES: ${DB_NAMES}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_USER_PASSWORD}
      DB_DUMP_FREQ: ${DB_DUMP_FREQ}
      DB_DUMP_BEGIN: ${DB_DUMP_BEGIN}
      {{- if eq .Values.DB_DUMP_TARGET_REMOTE "true"}}
      DB_DUMP_TARGET: ${DB_DUMP_TARGET}
      {{- else }}
      DB_DUMP_TARGET: /backup
      {{- end }}
      DB_DUMP_DEBUG: ${DB_DUMP_DEBUG}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
