version: 2
catalog:
  name: RancherDB-backup
  version: 0.0.1-rancher1
  description: |
    RancherDB Backup
  questions:
    - variable: CATTLEDB_USER
      label: CATTLEDB USER
      description: |
        CATTLEDB USER
      required: true
      default: 'cattle'
      type: string
    - variable: CATTLEDB_USER_PASSWORD
      label: CATTLEDB user password
      description: |
        MySQL root password
      required: true
      default: ''
      type: string
    - variable: DB_DUMP_FREQ
      label: Database Dump Frequency
      description: |
        How often to do a dump, in minutes. Defaults to 1440 minutes, or once per day.
      required: true
      default: 60
      type: int
    - variable: DB_DUMP_TARGET
      label: Database Dump Directory on Host
      description: |
         Where to put the dump file, should be a directory. Supports three formats /, smb://hostname/share/path/ ,s3://bucketname/path
      required: true
      default: '/backups'
      type: string

services:
  rancherdb-backup:
    retain_ip: false
    scale: 1
    start_on_create: true
