version: 2
catalog:
  name: RancherDB-backup
  version: 0.0.1-rancher1
  description: |
    RancherDB Backup
  questions:
    - variable: DB_SERVER
      label: MySQL Server host
      description: |
        NMySQL Server hostname or IP address
      required: true
      default: 'mysql'
      type: string
    - variable: DB_NAMES
      label: Names of databases to dump
      description: |
        Names of databases to dump; defaults to all databases in the database server
      required: false
      type: string
    - variable: MYSQL_USER
      label: MYSQL USER
      description: |
        MySQL USER - shoudl be a user with backup privileges
      required: true
      type: string
    - variable: MYSQL_USER_PASSWORD
      label: MySQL user password
      description: |
        MySQL password
      required: true
      type: string
    - variable: DB_DUMP_FREQ
      label: Database Dump Frequency
      description: |
        How often to do a dump, in minutes. Defaults to 1440 minutes, or once per day.
      required: true
      default: 60
      type: int
    - variable: DB_DUMP_BEGIN
      label: What time to do the first dump
      description: |
        What time to do the first dump. Defaults to immediate. Must be in one of two formats HHMM or +MM
      required: true
      default: '+0'
      type: string
    - variable: DB_DUMP_TARGET_REMOTE
      label: Database Dump to remote target ?
      description: |
         Is the dump target a remote ?
      required: true
      default: false
      type: boolean
    - variable: DB_DUMP_TARGET
      label: Database Dump target (local volume mapping or remote)
      description: |
         Where to put the dump file, should be a directory. Supports formats local host volume path  smb://hostname/share/path/ ,s3://bucketname/path
      required: true
      default: '/backup'
      type: string
    - variable: LOCAL_SCRIPTS
      label: Post backup scripts path
      description: |
         Where to look for post abckup scripts
      required: true
      default: ''
      type: string
    - variable: DB_DUMP_DEBUG
      label: Database Dump Debug ?
      description: |
         If set to true, print copious shell script messages to the container log. Otherwise only basic messages are printed
      required: true
      default: false
      type: boolean


services:
  rancherdb-backup:
    retain_ip: false
    scale: 1
    start_on_create: true
