version: 2
catalog:
  name: RancherDB-backup
  version: 0.0.1-rancher1
  description: |
    RancherDB Backup
  questions:
    - variable: DB_SERVER
      label: MySQL Server host
      description: |
        NMySQL Server hostname or IP address
      required: true
      default: 'mysql'
      type: string
    - variable: DB_NAMES
      label: Names of databases to dump
      description: |
        Names of databases to dump; defaults to all databases in the database server
      required: false
      type: string
    - variable: CATTLEDB_USER
      label: CATTLEDB USER
      description: |
        CATTLEDB USER
      required: true
      default: 'cattle'
      type: string
    - variable: CATTLEDB_USER_PASSWORD
      label: CATTLEDB user password
      description: |
        MySQL root password
      required: true
      default: ''
      type: string
    - variable: DB_DUMP_FREQ
      label: Database Dump Frequency
      description: |
        How often to do a dump, in minutes. Defaults to 1440 minutes, or once per day.
      required: true
      default: 60
      type: int
    - variable: DB_DUMP_BEGIN
      label: What time to do the first dump
      description: |
        What time to do the first dump. Defaults to immediate. Must be in one of two formats HHMM or +MM
      required: true
      default: '+0'
      type: string
    - variable: DB_DUMP_TARGET
      label: Database Dump Directory on Host
      description: |
         Where to put the dump file, should be a directory. Supports three formats /, smb://hostname/share/path/ ,s3://bucketname/path
      required: true
      default: '/backups'
      type: string
    - variable: DB_DUMP_DEBUG
      label: Database Dump Debug ?
      description: |
         If set to true, print copious shell script messages to the container log. Otherwise only basic messages are printed
      required: true
      default: false
      type: boolean


services:
  rancherdb-backup:
    retain_ip: false
    scale: 1
    start_on_create: true
