.catalog:
  name: Gitlab Community
  version: "9.4.5-ce.0"
  description: |
    Gitlab CE is a free GitHub alternative (with host volumes)
  minimum_rancher_version: v0.56.0
  maintainer: "The Teknologist <teknologist@gmail.com>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "gitlab_omnipus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'https://'
      required: true
      type: "string"
      options:
        - 'https://'
        - 'http://'
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
    - variable: "https_port"
      description: "HTTPS port to expose on host. Will be used to bind TCP"
      label: "HTTPS port:"
      required: true
      default: 443
      type: "string"
    - variable: "ssh_port"
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH port:"
      required: true
      default: 22
      type: "string"
    - variable: "opt_gitlab"
      description: "/var/opt/gitlab host volume path"
      label: "/var/opt/gitlab:"
      required: true
      default: "/var/opt/gitlab"
      type: "string"
    - variable: "log_gitlab"
      description: "/var/log/gitlab host volume path"
      label: "/var/log/gitlab:"
      required: true
      default: "/var/log/gitlab"
      type: "string"
    - variable: "etc_gitlab"
      description: "/etc/gitlab host volume path"
      label: "/etc/gitlab:"
      required: true
      default: "/etc/gitlab"
      type: "string"
    - variable: "gitlab_backups"
      description: "/var/opt/gitlab/backups host volume path"
      label: "/var/opt/gitlab/backups:"
      required: true
      default: "/var/opt/gitlab/backups"
      type: "string"
    - variable: "gitlab_secrets_backups"
      description: "/secret/gitlab/backups host volume path"
      label: "/secret/gitlab/backups:"
      required: true
      default: "/secret/gitlab/backups"
      type: "string"


gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true
