.catalog:
  name: "Nginx"
  version: "stable-alpine"
  description: "Nginx (pronounced engine-x) is an open source reverse proxy server"
  uuid: nginx-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: nginx_conf_path
      description: "Path to a nginx.conf file on host"
      label: "nginx.conf path"
      required: false
      default: "/etc/nginx/nginx.conf"
      type: "string"
    - variable: nginx_confd_path
      description: "Path to a conf.d directory on host for virtual hosts config"
      label: "conf.d path"
      required: false
      default: "/etc/nginx/conf.d"
      type: "string"
    - variable: http_ip
      description: "http ip to publish to"
      label: "Http IP to Publish to"
      required: true
      default: "127.0.0.1"
      type: "string"
    - variable: http_port
      description: "http port to publish"
      label: "Http Port"
      required: true
      default: "8080"
      type: "int"
    - variable: https_port
      description: "https port to publish"
      label: "Https Port"
      required: true
      default: "8443"
      type: "int"
    - variable: certs_path
      description: "Path to a directory with ssl certs"
      label: "ssl certs directory path"
      required: false
      default: "/ssl"
      type: "string"

services:
  nginx-proxy:
    scale: 1
    health_check:
      # Which port to perform the check against
      port: 80
      # For TCP, request_line needs to be '' or not shown
      # TCP Example:
      # request_line: ''
      request_line: GET / HTTP/1.0
      # Interval is measured in milliseconds
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      # Strategy for what to do when unhealthy
      strategy: recreate
      healthy_threshold: 2
      # Response timeout is measured in milliseconds
      response_timeout: 2000
