version: '2'
catalog:
  name: "MongoDB"
  version: "3.2-teknologism5"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
    - variable: host_label
      label: "Host Label to MongoDB Tags"
      description: |
        Host label to use as MongoDB 'value' tag.
        Example: 'database'
      required: false
      type: "string"
      default: "mongodb=true"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
    - variable: mongo_scale
      description: "How many containers the MongoDB will scale to?"
      label: "mongo scale"
      type: "int"
      required: true
      default: "3"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
mongo-cluster:
  scale: ${mongo_scale}
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
  health_check:
    response_timeout: 5000
    healthy_threshold: 2
    port: 27017
    unhealthy_threshold: 3
    initializing_timeout: 120000
    interval: 5000
    reinitializing_timeout: 120000
