.catalog:
  name: "Gogs"
  version: "latest"
  description: "A painless self-hosted Git service"
  uuid: gogs-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the mysql server"
      label: "Public Port"
      required: true
      default: "3306"
      type: "int"
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080"
      type: "int"
    - variable: ssh_port
      description: "ssh port to access gogs cli"
      label: "SSH Port"
      required: true
      default: "222"
      type: "int"
    - variable: gogs_data
      description: "Gogs data Host path"
      label: "Gogs data Host path"
      required: true
      default: ""
      type: "string"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: ""
      type: "password"
    - variable: mysql_data
      description: "Host /var/lib/mysql path"
      label: "Mysql data host path"
      required: true
      default: ""
      type: "string"
services:
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  gogs:
    scale: 1
    start_on_create: true
    health_check:
      port: 3000
      interval: 2000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET / HTTP/1.0
      healthy_threshold: 2
      response_timeout: 2000
