gitlab-server:
  ports:
  - 172.17.0.1:22:22/tcp
  - 127.0.0.1:${http_port}:80/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:9.5.3-ce.0
  volumes_from:
  - gitlab-data
  ulimits:
    nproc: 131072
    core: 0
    sigpending: 62793
    nofile:
      soft: 60000
      hard: 60000
  sysctls:
    net.core.somaxconn: '1024'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
    GITLAB_FILEMAX: 1000000,
    TZ: "UTC"
gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:9.5.3-ce.0
  volumes:
  - ${etc_gitlab}:/etc/gitlab
  - ${log_gitlab}:/var/log/gitlab
  - ${opt_gitlab}:/var/opt/gitlab
  - ${gitlab_backups}:/var/opt/gitlab/backups
  - ${gitlab_secrets_backups}:/secret/gitlab/backups
