web:
  image: nginx:stable-alpine
  volumes:
  - ${nginx_conf_path}:/etc/nginx/nginx.conf:ro
  volumes_from:
  - ssl-certs
  ports:
  - "80:80"
  - "443:443"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: ssl-certs

ssl-certs:
  image: rawmind/alpine-volume:0.0.2-1
  environment:
    SERVICE_GID: '0'
    SERVICE_UID: '0'
    SERVICE_VOLUME: /ssl
  volumes:
  - ${certs_path}:/ssl:ro
  labels:
    io.rancher.container.start_once: 'true'
