web:
  image: nginx:stable-alpine
  volumes:
   -  ${nginx_conf_path}:/etc/nginx/nginx.conf
  volumes_from:
   - ssl-certs
   - nginx-config
  ports:
   - "${http_port}:80"
   - "${https_port}:443"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: ssl-certs, nginx-config

ssl-certs:
  image: rawmind/alpine-volume:0.0.2-1
  network_mode: none
  environment:
    SERVICE_GID: '0'
    SERVICE_UID: '0'
    SERVICE_VOLUME: /ssl
  volumes:
    - ${certs_path}:/ssl
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name

nginx-config:
  image: rawmind/alpine-volume:0.0.2-1
  network_mode: none
  environment:
    SERVICE_GID: '0'
    SERVICE_UID: '0'
    SERVICE_VOLUME: /etc/nginx/conf.d
  volumes:
    - ${nginx_confd_path}:/etc/nginx/conf.d
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
